### ISSUE TITLE
Stuck in command mode

### ISSUE THREAD

**Issue by MVoloshin71** [bochs-emu/Bochs#427] opened 2024-12-23 20:50 UTC
Hello! I've compiled Bochs 2.8 for Android using Android-SDL by Pelya (https://github.com/pelya/commandergenius)\
I'd like to be able to change diskettes at runtime. Using F7 I successfully get to "Command mode" and Shift-C brings me into "Bochs Runtime Options" window. I can type any number but cannot get back from this menu ("Enter" key does nothing for some reason). Do you have any ideas?
P.S. "Enter" key works in guest operating systems just fine

**Comment by stlintel** [comment] 2024-12-24 06:23
We don't support Android-SDL by Pelya
I wish we would have Android port cleanly contributed to use but it is not.
Why won't you talk to author of this port ?

**Comment by stlintel** [comment] 2024-12-24 06:24
BTW correct clickable link [](https://github.com/pelya/commandergenius)

**Comment by MVoloshin71** [comment] 2024-12-24 07:06
> BTW correct clickable link [here](https://github.com/pelya/commandergenius) It doesn't point to Bochs Android port, can you explain what do you do exactly and how Bochs is related ?

I'll describe in details what I was doing once I'm home

**Comment by MVoloshin71** [comment] 2024-12-25 05:54
@stlitel, I have built Bochs 2.8 from source using libSDL from pelya (it's like an "environment" for running SDL applications on Android). I didn't touch Bochs sources itself, it was built as is (see attached APK).

I wanted to change floppy image at runtime, so I switched to Command mode using F7 key and then Shift-C in order to get to Options Menu (see screenshot).

![Screenshot_20241224-143656_Bochs Core](https://github.com/user-attachments/assets/8758937f-a483-4c31-a7d6-fff8aa0bdcab)

I can type anything from keyboard here, but I'm unable to continue simulation or do anything else as pressing Enter key after typing corresponsing number have no effect. Bochs 2.6 built with same library didn't have this problem, so I assume it might be an issue with Bochs itself, not pelya's libSDL.

[bochs-2.8.0-core-debug.zip](https://github.com/user-attachments/files/18243667/bochs-2.8.0-core-debug.zip)

**Comment by Vort** [comment] 2024-12-25 06:44
@MVoloshin71 there are two different Enter keys on keyboard. Can you try pressing other one?
I can reproduce this problem on Windows, but only with one of the keys. Other one works fine.

**Comment by MVoloshin71** [comment] 2024-12-25 07:15
> @MVoloshin71 there are two different Enter keys on keyboard. Can you try pressing other one? I can reproduce this problem on Windows, but only with one of the keys. Other one works fine.

Yes, ypu were right. KP_ENTER doesn't work while RETURN works right. "Enter" key on OSK seems to act as KP_ENTER for some reason

**Comment by Vort** [comment] 2024-12-25 07:44
This change works for me:
```diff
diff --git a/bochs/gui/sdl.cc b/bochs/gui/sdl.cc
index 1d57db817..49c383cf3 100644
--- a/bochs/gui/sdl.cc
+++ b/bochs/gui/sdl.cc
@@ -767,7 +767,8 @@ void bx_sdl_gui_c::handle_events(void)
           SDLKey keysym = sdl_event.key.keysym.sym;
           Bit8u ascii = (Bit8u)sdl_event.key.keysym.unicode;
           if (((keysym >= SDLK_SPACE) && (keysym < SDLK_DELETE)) ||
-              (keysym == SDLK_RETURN) || (keysym == SDLK_BACKSPACE)) {
+              (keysym == SDLK_RETURN) || (keysym == SDLK_KP_ENTER) ||
+              (keysym == SDLK_BACKSPACE)) {
             if (ascii < 0x80) {
               console_key_enq(ascii);
             } 
```
Can you check?

**Comment by MVoloshin71** [comment] 2024-12-25 13:13
> This change works for me:
> 
> ```diff
> diff --git a/bochs/gui/sdl.cc b/bochs/gui/sdl.cc
> index 1d57db817..49c383cf3 100644
> --- a/bochs/gui/sdl.cc
> +++ b/bochs/gui/sdl.cc
> @@ -767,7 +767,8 @@ void bx_sdl_gui_c::handle_events(void)
>            SDLKey keysym = sdl_event.key.keysym.sym;
>            Bit8u ascii = (Bit8u)sdl_event.key.keysym.unicode;
>            if (((keysym >= SDLK_SPACE) && (keysym < SDLK_DELETE)) ||
> -              (keysym == SDLK_RETURN) || (keysym == SDLK_BACKSPACE)) {
> +              (keysym == SDLK_RETURN) || (keysym == SDLK_KP_ENTER) ||
> +              (keysym == SDLK_BACKSPACE)) {
>              if (ascii < 0x80) {
>                console_key_enq(ascii);
>              } 
> ```
> 
> Can you check?

It doesn't work if enter key pressed on OSK( But it works if I map some hardware key to SDL_RETURN or SDL_KP_ENTER. So, there's something wrong with OSK

**Comment by Vort** [comment] 2024-12-25 13:53
@MVoloshin71 what about this one?

```diff
diff --git a/bochs/gui/sdl.cc b/bochs/gui/sdl.cc
index 1d57db817..a3648a34d 100644
--- a/bochs/gui/sdl.cc
+++ b/bochs/gui/sdl.cc
@@ -767,11 +767,14 @@ void bx_sdl_gui_c::handle_events(void)
           SDLKey keysym = sdl_event.key.keysym.sym;
           Bit8u ascii = (Bit8u)sdl_event.key.keysym.unicode;
           if (((keysym >= SDLK_SPACE) && (keysym < SDLK_DELETE)) ||
-              (keysym == SDLK_RETURN) || (keysym == SDLK_BACKSPACE)) {
+              (keysym == SDLK_BACKSPACE)) {
             if (ascii < 0x80) {
               console_key_enq(ascii);
             }
           }
+          else if ((keysym == SDLK_RETURN) || (keysym == SDLK_KP_ENTER)) {
+            console_key_enq(13); // because of Android
+          }
           break;
         }
         // mouse capture toggle-check 
```

**Comment by MVoloshin71** [comment] 2024-12-25 14:19
> @MVoloshin71 what about this one?
> 
> ```diff
> diff --git a/bochs/gui/sdl.cc b/bochs/gui/sdl.cc
> index 1d57db817..a3648a34d 100644
> --- a/bochs/gui/sdl.cc
> +++ b/bochs/gui/sdl.cc
> @@ -767,11 +767,14 @@ void bx_sdl_gui_c::handle_events(void)
>            SDLKey keysym = sdl_event.key.keysym.sym;
>            Bit8u ascii = (Bit8u)sdl_event.key.keysym.unicode;
>            if (((keysym >= SDLK_SPACE) && (keysym < SDLK_DELETE)) ||
> -              (keysym == SDLK_RETURN) || (keysym == SDLK_BACKSPACE)) {
> +              (keysym == SDLK_BACKSPACE)) {
>              if (ascii < 0x80) {
>                console_key_enq(ascii);
>              }
>            }
> +          else if ((keysym == SDLK_RETURN) || (keysym == SDLK_KP_ENTER)) {
> +            console_key_enq(13); // because of Android
> +          }
>            break;
>          }
>          // mouse capture toggle-check 
> ```

It worked, but without "else". P.S. I understood that it isnt Bochs fault, it's lack of suitable keyboard map in pelya's libSDL implementation

**Comment by Vort** [comment] 2024-12-25 14:39
> It worked, but without "else"

> With your fix both modes work

What do you mean?
1. It works with and without "else"?
2. Or it does not work with "else"?

**Comment by MVoloshin71** [comment] 2024-12-25 14:40
> > It worked, but without "else"
> 
> > With your fix both modes work
> 
> What do you mean?
> 
> 1. It works with and without "else"?
> 2. Or it does not work with "else"?

I corrected my answer, it worked as is

**Comment by MVoloshin71** [comment] 2024-12-25 14:45
@Vort ,
I'd like to ask a question. Do I understand everyrhing right?
 - guest OS inside Bochs always receives PC ASCII codes.
 - "Command Mode" receives host (Android) keyboard ASCII codes as is.

**Comment by Vort** [comment] 2024-12-25 15:12
I think for guest OS:
1. Conversion `SDLK_RETURN` -> `BX_KEY_ENTER` happens [here](https://github.com/bochs-emu/Bochs/blob/eb1978f0127ba0b9226e277914833adb8fa71a89/bochs/gui/sdl.cc#L191);
2. Keyboard device makes [this conversion](https://github.com/bochs-emu/Bochs/blob/eb1978f0127ba0b9226e277914833adb8fa71a89/bochs/iodev/scancodes.cc#L479-L483);
3. Guest OS converts code from keyboard device to ASCII code.

In "Command mode", guest OS is not involved, so conversion happens in more direct way.

However, I make such conclusion just from brief look at source code.
@vruppert should know this mechanism better.

**Comment by MVoloshin71** [comment] 2024-12-25 18:18
@Vort , finally I had to omit "else", because otherwise logic does not work (idk why)

```
if (((keysym >= SDLK_SPACE) && (keysym < SDLK_DELETE)) ||
              (keysym == SDLK_RETURN) || (keysym == SDLK_BACKSPACE)) {
            if (ascii < 0x80) {
              console_key_enq(ascii);
            }
            #ifdef ANDROID
            if (keysym == SDLK_RETURN) {
              console_key_enq(13);
            }
            #endif
          }
```

**Comment by vruppert** [comment] 2024-12-25 20:20
I have now applied the latest version of the fix for Android to the github repository with a small change. A few months ago we have changed all appearances of ANDROID to __ANDROID__, since this one seems to be the official macro. Please check if it works correctly.

P.S.: The Bochs developers are interested in having an official Android port. It would be nice when you could give us some infos how you did it (system and software requirements, steps to build). We have some stuff in the build/android folder, but I guess it needs to be updated or rewritten.

**Comment by MVoloshin71** [comment] 2024-12-25 21:29
@vruppert , yeah, I'll provide build steps soon

**Comment by MVoloshin** [comment] 2024-12-26 20:09
@vruppert , https://github.com/bochs-emu/Bochs/pull/433

**Comment by vruppert** [comment] 2024-12-27 07:03
I have now merged the PR into Bochs repository after a quick look. I'll try to follow the steps soon.
What about this issue? If everything's okay, you should close it. We can use the discussion forum to talk about the Android port after my first try.

**Closed** 2024-12-27 10:41 UTC
