### ISSUE TITLE
0xc0000417 crash while exiting with uhci enabled

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#25] opened 2022-12-28 13:49 UTC
Version: 2.7
Host OS: Windows 7 SP1 x64

To reproduce problem, start following config file:
```
plugin_ctrl: usb_uhci=true
usb_uhci: enabled=1, port1=mouse, options1=none, port2=keyboard, options2=none
```
Then select "Kill simulation" when "No bootable device" error appears.
Result:
![image](https://user-images.githubusercontent.com/1242858/209821317-743818fd-43e3-4764-9ae2-b5090c6c3e37.png)

---

Also I noticed another crash, not sure if it is related (probably not), but will show it anyway _(I don't know how to reproduce it)_:
![image](https://user-images.githubusercontent.com/1242858/209821996-c64a9b58-01dc-47cb-be1f-5e3315a271e7.png)

**Comment by stlintel** [comment] 2023-02-20 18:36
Hi,

Ben just merged huge USB code rewrite to Bochs main. Can you check if the problem disappear or still there ?

**Comment by Vort** [comment] 2023-02-20 18:40
Can I download fresh binaries somewhere?
I see that GitHub actions build fresh commits, but can't find how to download results of these builds.

**Comment by fysnet** [comment] 2023-03-14 23:46
Are you using a Windows version of Bochs? I have a binary I can upload to a temp page to let you try. 32-bit or 64-bit?

**Comment by Vort** [comment] 2023-03-15 05:54
@fysnet please upload binary compatible with Windows 7 SP1 x64.

**Comment by fysnet** [comment] 2023-03-15 20:40
Okay, I have a zipped down 64-bit version at: https://www.fysnet.net/temp/bochs.exe.zip
Please let me know if it works and if you still get this error you mention. If so, please explain in as much detail as possible.
Thank you,
Ben

**Comment by Vort** [comment] 2023-03-16 08:19
1. Crash still happens with new binary.
2. What was the result of your reproduction with the steps provided by me?
3. With new binary, instead of selecting "Kill simulation" in GUI, user should press Enter in CUI (selecting option "die").
4. You binary did not come with debugging information, becuse of it details will be not much detailed.
5. Crash happens inside this function:
![image](https://user-images.githubusercontent.com/1242858/225555551-6d39106c-a529-4f6d-9761-7f7a22bc3636.png)
With such stack trace:
```
bochs.exe!00000001402714f6()
bochs.exe!0000000140271475()
bochs.exe!0000000140271491()
bochs.exe!0000000140264ec5()
bochs.exe!0000000140212505()
bochs.exe!00000001401f27d1()
bochs.exe!000000014020cdb4()
bochs.exe!00000001401f4863()
bochs.exe!00000001401f430f()
bochs.exe!00000001401f43c4()
bochs.exe!00000001401f4f50()
bochs.exe!00000001400a3e95()
bochs.exe!00000001400a3ed7()
bochs.exe!0000000140164083()
bochs.exe!00000001400a291a()
bochs.exe!00000001400a0094()
bochs.exe!000000014009f43f()
bochs.exe!000000014009fc25()
bochs.exe!000000014016ce38()
bochs.exe!00000001400a8ba7()
bochs.exe!00000001400a038f()
bochs.exe!0000000140158aab()
bochs.exe!0000000140158e2c()
bochs.exe!0000000140159a19()
bochs.exe!000000014015470f()
bochs.exe!00000001400a2033()
bochs.exe!000000014021b3b0()
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()
```
You can see `c0000417` in CPU instructions by the way.

**Comment by fysnet** [comment] 2023-03-17 01:28
I uploaded a debug version, same link (https://www.fysnet.net/temp/bochs.exe.zip).
I can reproduce a very similar error when adding a device to an existing hub, then exiting. If I don't add a device to a hub, it exits without crashing. Once I add a device to the hub, it crashes on exiting.  I have narrowed the crash a bit, but don't know exactly where yet.
Thanks for your help.

**Comment by fysnet** [comment] 2023-03-17 04:22
I believe I found the error. I will investigate further to be sure, then upload a new binary for your to try. Give me a day or two.
Thanks, Ben

**Comment by fysnet** [comment] 2023-03-18 00:19
Since you show that you obviously know how to use the debug capabilities, it surprises me you haven't downloaded the source and compiled it yourself.  :-)

Anyway, I believe I found the error. I have uploaded the binary (both release and debug), https://www.fysnet.net/temp/bochs.exe.zip

Please try it and see if this fixes the issue.

Thanks,
Ben

**Comment by Vort** [comment] 2023-03-18 00:26
> Since you show that you obviously know how to use the debug capabilities, it surprises me you haven't downloaded the source and compiled it yourself. :-)

I use Visual Studio 2015 and this project have Visual Studio 2019 project files, most likely there will be incompatibilities.

> Please try it and see if this fixes the issue.

No crash with fresh binaries. Thanks.
Should this bugreport be closed then?

**Comment by fysnet** [comment] 2023-03-18 00:37
I have started a Pull Request to update the Bochs source. Thank you for your help, you may close this bug report.

**Closed** 2023-03-18 00:38 UTC
