### ISSUE TITLE
CD-ROM not found with MS-DOS 6.22

### ISSUE THREAD

**Issue by stlintel** [bochs-emu/Bochs#103] opened 2023-10-18 13:54 UTC
### Discussed in https://github.com/bochs-emu/Bochs/discussions/102

<div type='discussions-op-text'>

<sup>Originally posted by **Vort** October 18, 2023</sup>
Hello.

I was using `teac_cdi.sys` driver with DOS for a long time.
It always worked for me, both on real hardware and with virtual machines.

But I can't get it to work with Bochs for some reason.
Not sure if because of some my mistake or because of bugs in Bochs.

Can anyone look at my virtual machine ([bochs_dos_cd.zip](https://github.com/bochs-emu/Bochs/files/12995200/bochs_dos_cd.zip)) and say what's wrong with CD support there?

![bochs_no_cd](https://github.com/bochs-emu/Bochs/assets/1242858/d1d999ab-da50-43a3-bd10-e16d2999e6b3)</div>

**Comment by stlintel** [comment] 2023-10-18 13:55
Looks like these errors may be related to the problem:
00313080588e[HD    ] IO read(0x01f0) with drq == 0: last command was 00h
00337796783e[HD    ] IO read(0x0170) with drq == 0: last command was 00h

**Comment by fysnet** [comment] 2023-10-19 01:30
Here is my thought on this, and with a little research I found:

If you count how many lines of
`00313080588e[HD ] IO read(0x01f0) with drq == 0: last command was 00h`
there are between the last command (which is actually a `0xEC` command, but since a write to `0x1F7` on a non-existent device is ignored, the command register is still `00h` as shown in the log line above) and the next command, you will see that it is 256 lines. Since you (normally) read a 16-bit value 256 times per `0xEC` command, the TEAC driver is trying to read the `IDENTIFY` command, though Bochs doesn't have any data for it to read. 

Why? Because Bochs supports up to ATAPI-4, which when the ATAPI device receives a `0xEC` command, it is to abort, not reply with 256 words.

However, with that being said, Bochs aborts the `IDENTIFY` command to the CD-ROM, which the TEAC driver takes as an error. The error line _stlintel_ mentioned above is actually shown when the TEAC driver tries to read the `IDENTIFY` command from channel 1, a non-existent drive.

Now, why does it work on real (old) hardware?

DOS 6.22 was released in 1994, ATAPI-4 was released in 1998. In 1994, all devices responded with 256 words to the `0xEC` command. I don't know the exact values of this old `IDENTIFY` block, so I can't confirm or deny that it does or does not like the items returned. I even hacked `harddrv.cc` just a bit to return mostly zeros, except for `word 0`, and the TEAC driver still didn't recognize the drive. (The TEAC driver has a copyright of 1996, still before the 1998 release of ATAPI-4)

What other emulation did you use that did work? QEMU won't even boot the drive.

In my opinion, this isn't a cause worth fixing. I spent a couple of hours looking into this, mainly because I wanted to see if I could get it to work with a few hacks.

Just my opinion though,
Ben

**Comment by Vort** [comment] 2023-10-19 06:44
During further tests I have found that I forgot to include `mscdex.exe`.
So here is updated virtual machine archive: [bochs_dos_cd2.zip](https://github.com/bochs-emu/Bochs/files/13038782/bochs_dos_cd2.zip).
But test results with previous version are still valid.

> What other emulation did you use that did work? QEMU won't even boot the drive.

QEMU most likely just do not understand disk format used by Bochs.
I used bximage to make `.vmdk` file, which more VMs can understand.

However, result is "not found" with QEMU 7.0.0.
Correct detection happens with VirtualBox 6.1.36 and VMware Workstation 12.5.2.

![image](https://github.com/bochs-emu/Bochs/assets/1242858/1b3213fb-2a4e-4044-a709-295eb242841a)

> In my opinion, this isn't a cause worth fixing.

In my opinion, Bochs is useful for history preservation purposes:
To allow executing old software without buying old hardware.
In such case, more sofware can run, the better.
But I can agree that this is a low priority problem.

**Comment by Vort** [comment] 2023-10-19 09:58
> In 1994, all devices responded ...

This is how `teac_cdi.sys` driver works with device from 2003 (CRW-5232AS):
![CRW-5232AS](https://github.com/bochs-emu/Bochs/assets/1242858/b2e4a6ef-3f40-4292-9cc7-14bc686314eb)
![teac_cdi_realhw](https://github.com/bochs-emu/Bochs/assets/1242858/2fbb958c-e0fb-41c0-b568-c07ddccc50ae)

**Comment by fysnet** [comment] 2023-10-19 22:21
Darn, now you got me intrigued...  :-)
\<sarcasm\>Thanks!\</sarcasm\>

Just kidding. Maybe I can find something.

**Comment by fysnet** [comment] 2023-10-21 21:05
Please see PR #105, for an addition that makes this driver work.

The TEAC driver relies on the fact the drive it was designed for sets the interrupt register, more specifically, the i_o bit of that register, so that it can determine the direction of transfer for the 0xA1 command, which is a read-only command. Without this assumption and the i_o bit specifying the direction, the TEAC driver tried to write 256 words rather than read 256 words.

This PR also adds a fix to the DEVICE RESET command which should set the DRV_RDY bit to zero, something it hadn't done before.

Both of these fixes were required for this TEAC driver to work, the former as a Device Specific fix, the latter as an all device fix.

**Comment by fysnet** [comment] 2023-10-21 23:52
I also wanted to mention and repeat what stlintel had said, thank you for your tests. It is appreciated.

**Comment by Vort** [comment] 2023-10-22 08:48
With d827f3839fb1426748f21a44f4cfac0893a4de80 CD-ROM is detected correcty. Thank you.

**Closed** 2023-10-22 08:56 UTC
