### ISSUE TITLE
The screen display during the Debian 11 startup stage is abnormal

### ISSUE THREAD

**Issue by lgj1107** [bochs-emu/Bochs#257] opened 2024-02-04 04:38 UTC
![1](https://github.com/bochs-emu/Bochs/assets/3366897/7565f40a-79fa-473a-a7fc-e908a54e72d4)

The debian IMG file is too large to upload。

> 00469593925i[BXVGA ] VBE set xres (800)
00469593944i[BXVGA ] VBE set yres (600)
00469593963i[BXVGA ] VBE set bpp (24)
00469593982i[BXVGA ] VBE enabling x 800, y 600, bpp 24, 1440000 bytes visible
03965682030i[BXVGA ] VBE disabling
04001249813e[CPU0  ] RDMSR: Unknown register 0x1a0
04479250000p[XGUI  ] >>PANIC<< POWER button turned off.

It seems that VBE is not working properly.

bochsrc、bochsout
[bochsrc.zip](https://github.com/bochs-emu/Bochs/files/14155508/bochsrc.zip)

**Comment by Vort** [comment] 2024-02-04 08:27
1. Do you mean OS needs to be installed or it is enough to load it from DVD?
2. Can you try removing `,slot1=pcivga` from your config file?

**Comment by lgj1107** [comment] 2024-02-04 08:51
Yes, you need to install debian.  I just tried debian 12, and I encountered the same problem as with debian 11

After deleting slot1=pcivga, the screen is black

**Comment by Vort** [comment] 2024-02-04 09:09
Looks like you are using old `VGABIOS-lgpl-latest` from version 2.7.
With newer VGABIOS I can't even start installation with `slot1=pcivga`.
Hard to say which version is better.

---

@vruppert looks like regression appeared in some of newer VGABIOSes.
`debian-11.8.0-amd64-DVD-1.iso` shows black screen with `slot1=pcivga` and latest VGABIOS.
With VGABIOS from Bochs 2.7, image appears normally:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/998a3ec3-1e2e-46af-aaff-61377ae53c5b)

**Comment by lgj1107** [comment] 2024-02-04 09:18
You need to install Debian and then launch it from the IMG file.  You should see the problem screen

**Comment by Vort** [comment] 2024-02-04 09:38
I understood it. But I think regression with `slot1=pcivga` should be fixed first.

**Comment by vruppert** [comment] 2024-02-04 11:06
I can confirm that the DVD boot issue exists with Bochs VBE / PCI. With Cirrus and Banshee the boot screen appears normally. I guess the LFB detection in function 0x4f01 causes this issue. More tests will follow when it is fixed.

**Comment by vruppert** [comment] 2024-02-04 13:03
The boot issue with VBE is now fixed in VGABIOS repository. Now I'll try to install Debian.

**Comment by vruppert** [comment] 2024-02-04 18:47
Update: After installing Debian 11 I tried to boot with different setups. With Bochs VBE it shows the display as reported above. With the Cirrus card both our VGABIOS as well as the original Cirrus VGABIOS showing a blinking text screen with unreadable characters. Only the Banshee/Voodoo3 card seems to behave normally. With our VGABIOS a text mode screen shows the boot progress and finally the graphical login screen appears. First of all I'll have a look at the Cirrus emulation, since it's behavior doesn't depend on the VGABIOS.

**Comment by vruppert** [comment] 2024-02-06 20:02
Update: I have now applied a workaround for the save/restore function of the GRUB bootloader. It works with Bochs VBE only, since there is no easy way to make it work with Cirrus. GRUB handles known and unknown graphics adapters differently. For unknown graphics chipsets it turns on a VBE mode and finally turns on the text mode before the booting OS takes control of the machine. For known graphics chipsets (like Bochs VBE and Cirrus) the behavior is different. It saves the register settings and the first 8 K of each memory plane and restores all of it when it's job is done. Bochs has two issues with this. Accessing VGA memory with the PCI framebuffer is not yet possible and the Bochs VGA memory layout is different from the one that GRUB expects. In the selected "chain4" access mode the memory plane selector is on bit 0 and 1 of the address, but Bochs uses bit 16 and 17. A rewrite of the memory handling and update code. My workaround only handles this GRUB behavior and it's only for Bochs VBE.

**Comment by vruppert** [comment] 2024-02-24 19:48
After enabling the VGA_MEM_FIX stuff this issue should be fixed for both Bochs VBE and Cirrus graphics adapter.

**Closed** 2024-03-01 12:20 UTC
